Hw7
Dimsonpip/loftmoney pull request #9
Opened 2020-04-13 21:29 UTC by Dimsonpip

ДЗ 7 с дополнительной альфа анимацией экрана авторизации.

2020-04-14 09:24 UTC, xsoboledux requested changes

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/auth/AuthActivity.java
> +    private List<Disposable> disposables = new ArrayList<>();
Можно использовать CompositeDisposable, это удобная структура данных для подписок

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/auth/AuthActivity.java
> +
пустая строка

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/auth/AuthActivity.java
> +                .subscribeOn(Schedulers.computation())
Здесь лучше использовать Schedulers.io()

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/auth/AuthActivity.java
> +                        finish();
Зачем здесь finish?

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/main/ChargeFragment.java
> +        String authToken = sharedPreferences.getString(AuthResponse.AUTH_TOKEN_KEY, "");
i/o операции надо делать на другом потоке, иначе может заблокироваться ui thread

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/main/IncomeFragment.java
> +        String authToken = sharedPreferences.getString(AuthResponse.AUTH_TOKEN_KEY, "");
То же самое

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/second/AddItemActivity.java
> +        String authToken = sharedPreferences.getString(AuthResponse.AUTH_TOKEN_KEY, "");
и тут

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/second/AddItemActivity.java
> +    private void setLoading(Boolean state){
state лучше назвать isLoading, проще для понимания

2020-04-14 09:24 UTC, xsoboledux commented on app/src/main/java/com/dimsonpip/loftmoney/screens/splash/SplashActivity.java
> +        String authToken = sharedPreferences.getString(AuthResponse.AUTH_TOKEN_KEY, "");
это я уже видел несколько раз
Можно вынести в отдельный класс, например PrefHelper и избедать дублирования

2020-04-15 16:15 UTC, Dimsonpip commented on app/src/main/java/com/dimsonpip/loftmoney/screens/auth/AuthActivity.java
> +    private List<Disposable> disposables = new ArrayList<>();
При этом появляется ошибка HTTP FAILED: java.io.IOException: Canceled.

2020-04-15 16:16 UTC, Dimsonpip commented on app/src/main/java/com/dimsonpip/loftmoney/screens/main/ChargeFragment.java
> +        String authToken = sharedPreferences.getString(AuthResponse.AUTH_TOKEN_KEY, "");
Я, конечно, тоже вижу, что это кусок повторяется. Но придумать что-то с новым классом, чтобы это заработало не вышло. Ну и с потоками вообще не получилось ничего.

2020-04-15 16:50 UTC, Dimsonpip commented on app/src/main/java/com/dimsonpip/loftmoney/screens/splash/SplashActivity.java
> +        String authToken = sharedPreferences.getString(AuthResponse.AUTH_TOKEN_KEY, "");
Я, конечно, тоже вижу, что это кусок повторяется. Но придумать что-то с новым классом, чтобы это заработало не вышло.  Мы в этом классе authToken должны получить, чтобы потом передать в нужные места?

2020-04-17 13:54 UTC, merged